version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
    - POSTGRES_PASSWORD=admin
    networks:
      default:
        aliases:
          - localhost
    ports:
      - '5432:5432'
